// Maps English team names → emoji flag
export const COUNTRY_FLAGS: Record<string, string> = {
  "argentina": "🇦🇷",
  "australia": "🇦🇺",
  "bahrain": "🇧🇭",
  "belgium": "🇧🇪",
  "bolivia": "🇧🇴",
  "brazil": "🇧🇷",
  "cameroon": "🇨🇲",
  "canada": "🇨🇦",
  "chile": "🇨🇱",
  "colombia": "🇨🇴",
  "costa rica": "🇨🇷",
  "croatia": "🇭🇷",
  "cuba": "🇨🇺",
  "czech republic": "🇨🇿",
  "czechia": "🇨🇿",
  "denmark": "🇩🇰",
  "dr congo": "🇨🇩",
  "ecuador": "🇪🇨",
  "egypt": "🇪🇬",
  "el salvador": "🇸🇻",
  "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "france": "🇫🇷",
  "germany": "🇩🇪",
  "ghana": "🇬🇭",
  "greece": "🇬🇷",
  "guatemala": "🇬🇹",
  "haiti": "🇭🇹",
  "honduras": "🇭🇳",
  "hungary": "🇭🇺",
  "iran": "🇮🇷",
  "ir iran": "🇮🇷",
  "iraq": "🇮🇶",
  "italy": "🇮🇹",
  "ivory coast": "🇨🇮",
  "côte d'ivoire": "🇨🇮",
  "cote d'ivoire": "🇨🇮",
  "jamaica": "🇯🇲",
  "japan": "🇯🇵",
  "jordan": "🇯🇴",
  "kenya": "🇰🇪",
  "korea republic": "🇰🇷",
  "republic of korea": "🇰🇷",
  "south korea": "🇰🇷",
  "mali": "🇲🇱",
  "mexico": "🇲🇽",
  "morocco": "🇲🇦",
  "netherlands": "🇳🇱",
  "new zealand": "🇳🇿",
  "nigeria": "🇳🇬",
  "norway": "🇳🇴",
  "oman": "🇴🇲",
  "panama": "🇵🇦",
  "paraguay": "🇵🇾",
  "peru": "🇵🇪",
  "poland": "🇵🇱",
  "portugal": "🇵🇹",
  "qatar": "🇶🇦",
  "romania": "🇷🇴",
  "saudi arabia": "🇸🇦",
  "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "senegal": "🇸🇳",
  "serbia": "🇷🇸",
  "slovakia": "🇸🇰",
  "south africa": "🇿🇦",
  "spain": "🇪🇸",
  "suriname": "🇸🇷",
  "switzerland": "🇨🇭",
  "tunisia": "🇹🇳",
  "turkey": "🇹🇷",
  "ukraine": "🇺🇦",
  "united states": "🇺🇸",
  "united states of america": "🇺🇸",
  "usa": "🇺🇸",
  "uruguay": "🇺🇾",
  "uzbekistan": "🇺🇿",
  "venezuela": "🇻🇪",
  "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};

export function getFlag(enName: string): string {
  return COUNTRY_FLAGS[enName.toLowerCase()] ?? "🏳️";
}
